/**
 * The client-side filter, as a browser module. Emitted to filter.js.
 *
 * PROGRESSIVE ENHANCEMENT, NOT A FEATURE GATE. The brief asked for a
 * publication that is browsable AND queryable, and 494 pages carried no search
 * box, no filter and no form of any kind. Queryability existed, but only
 * through the CLI and the JSON API, which is a different audience from a person
 * reading a page.
 *
 * THE LIST IS THE PAGE AND THE FILTER IS DRAWN OVER IT, exactly as the 3D wall
 * is drawn over the thread list. The input is created BY THIS SCRIPT, so a
 * reader with JavaScript off never sees a control that does nothing, and every
 * row is present in the HTML either way. Nothing is fetched: the rows being
 * filtered are already on the page.
 *
 * Matching is a case-insensitive substring over the row's own text. No fuzzy
 * matching and no ranking, because a reader typing "opus" into a filter over a
 * list they can see wants the rows containing "opus" and nothing cleverer.
 */
export const FILTER_JS_PATH = 'filter.js';

export const FILTER_JS = `/* Generated by src/site/filter-js.ts. Do not edit. */
(function () {
  'use strict';

  /* Every table the page has marked as filterable. */
  var tables = document.querySelectorAll('table[data-filter]');
  if (tables.length === 0) return;

  tables.forEach(function (table) {
    var label = table.getAttribute('data-filter') || 'rows';
    var body = table.tBodies[0];
    if (!body) return;
    var rows = Array.prototype.slice.call(body.rows);
    if (rows.length < 2) return;

    var wrap = document.createElement('div');
    wrap.className = 'filter';

    var input = document.createElement('input');
    input.type = 'search';
    input.className = 'filter-input';
    input.placeholder = 'Filter ' + label;
    input.setAttribute('aria-label', 'Filter ' + label);
    /* Announced, so a screen reader hears the count change. */
    var count = document.createElement('span');
    count.className = 'filter-count';
    count.setAttribute('role', 'status');
    count.setAttribute('aria-live', 'polite');

    wrap.appendChild(input);
    wrap.appendChild(count);
    var host = table.closest('.table-scroll') || table;
    host.parentNode.insertBefore(wrap, host);

    /* Text is read once. These pages are static and the rows never change. */
    var haystacks = rows.map(function (r) {
      return (r.textContent || '').toLowerCase();
    });

    function apply() {
      var q = input.value.trim().toLowerCase();
      var shown = 0;
      for (var i = 0; i < rows.length; i++) {
        var hit = q === '' || haystacks[i].indexOf(q) !== -1;
        rows[i].hidden = !hit;
        if (hit) shown++;
      }
      count.textContent = q === '' ? '' : shown + ' of ' + rows.length;
    }

    input.addEventListener('input', apply);
    /* Escape clears, which is what every filter box a developer has used does. */
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') {
        input.value = '';
        apply();
      }
    });
  });
})();
`;
